export const categories = [
    "Electronics",
    "Fashion",
    "Video Games",
    "Books",
    "Home & Kitchen",
    "Beauty & Personal Care",
    "Sports & Outdoors",
    "Toys & Games",
    "Home",
    "Restricted", 
  ];
  
  export const subcategories = [
    "Mobile Phones",
    "Laptops",
    "Tablets",
    "Cameras",
    "TVs",
    "Headphones",
    "Smartwatches",
    "Pants",
    "Shirts",
    "Shoes",
    "Watches",
    "Sunglasses",
    "Bags",
    "Consoles",
    "Games",
    "Accessories",
    "Fiction",
    "Non-Fiction",
    "Children's Books",
    "Furniture",
    "Appliances",
    "Cookware",
    "Makeup",
    "Skincare",
    "Haircare",
    "Fragrances",
    "Personal Care",
    "Fitness",
    "Outdoor Recreation",
    "Team Sports",
    "Athletic Clothing",
    "Footwear",
    "Action Figures",
    "Dolls",
    "Board Games",
    "Puzzles",
    "Outdoor Play",
    "Bedding",
    "Bath",
    "Decor",
    "Lighting",
    "Storage",
    "Weapons",
  ];

  export const subsubcategories = [
    "iPhones",
    "Android Phones",
    "Windows Phones",
    "Basic Phones",
    "Ultrabooks",
    "Gaming Laptops",
    "Notebooks",
    "iPads",
    "Android Tablets",
    "DSLRs",
    "Point and Shoot",
    "Instant Cameras",
    "LED",
    "OLED",
    "QLED",
    "Over Ear",
    "In Ear",
    "On Ear",
    "Apple Watch",
    "Samsung Gear",
    "Fitbit",
    "Garmin",
    "Others",
    "Jeans",
    "Chinos",
    "Joggers",
    "Cargo Pants",
    "T-Shirts",
    "Polo Shirts",
    "Casual Shirts",
    "Formal Shirts",
    "Sneakers",
    "Loafers",
    "Boots",
    "Sandals",
    "Analog",
    "Digital",
    "Smart",
    "Aviators",
    "Wayfarers",
    "Round",
    "Square",
    "Backpacks",
    "Messenger Bags",
    "Duffel Bags",
    "Tote Bags",
    "PlayStation 5",
    "Xbox Series X/S",
    "Nintendo Switch",
    "PC",
    "Retro",
    "Action",
    "Adventure",
    "RPG",
    "Sports",
    "Strategy",
    "Controllers",
    "Headsets",
    "Charging Stations",
    "Cables",
    "Mystery",
    "Thriller",
    "Romance",
    "Science Fiction",
    "Fantasy",
    "Biography",
    "Self-Help",
    "Cooking",
    "History",
    "Travel",
    "Science",
    "Picture Books",
    "Early Readers",
    "Middle Grade",
    "Young Adult",
    "Sofas",
    "Beds",
    "Dining Tables",
    "Chairs",
    "Refrigerators",
    "Washing Machines",
    "Microwaves",
    "Air Conditioners",
    "Pots and Pans",
    "Bakeware",
    "Cooking Utensils",
    "Cutlery",
    "Foundation",
    "Lipstick",
    "Mascara",
    "Eyeshadow",
    "Cleansers",
    "Moisturizers",
    "Serums",
    "Masks",
    "Shampoo",
    "Conditioner",
    "Styling Products",
    "Hair Color",
    "Perfumes",
    "Colognes",
    "Body Sprays",
    "Toothpaste",
    "Deodorant",
    "Shaving Cream",
    "Body Wash",
    "Yoga",
    "Running",
    "Cycling",
    "Strength Training",
    "Cardio",
    "Camping",
    "Hiking",
    "Fishing",
    "Boating",
    "Soccer",
    "Basketball",
    "Football",
    "Baseball",
    "Shirts",
    "Shorts",
    "Jackets",
    "Socks",
    "Running Shoes",
    "Soccer Cleats",
    "Basketball Shoes",
    "Football Cleats",
    "Superheroes",
    "Star Wars",
    "Transformers",
    "Power Rangers",
    "Barbie",
    "Monopoly",
    "Scrabble",
    "Catan",
    "Ticket to Ride",
    "Jigsaw",
    "3D",
    "Wooden",
    "Swing Sets",
    "Trampolines",
    "Slides",
    "Water Guns",
    "Nerf",
    "Sandboxes",
    "Sheets",
    "Comforters",
    "Duvet Covers",
    "Pillows",
    "Towels",
    "Shower Curtains",
    "Bath Mats",
    "Bath Accessories",
    "Wall Art",
    "Mirrors",
    "Clocks",
    "Vases",
    "Ceiling Lights",
    "Floor Lamps",
    "Table Lamps",
    "Wall Lights",
    "Baskets",
    "Boxes",
    "Shelves",
    "Drawers",
    "Toy Weapons",
  ]